
import initTranslations from '@/app/i18n';
import CloseComp from '@/components/global/CloseComp/CloseComp';
import TranslationsProvider from '@/components/global/TranslationsProvider';
import SidebarPanel from '@/components/layout/SidebarPanel';
const i18nNamespace = ['Login'];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({children,params : { locale }}) {
  const { resources } = await initTranslations(locale,i18nNamespace);
 
  return (
    <div className={'dashboardLayout'}>
        <TranslationsProvider namespaces={i18nNamespace} locale={locale} resources={resources}>
          <SidebarPanel />
        </TranslationsProvider>
        
        <div className='contentLayout'>
          <CloseComp />
          {children}
        </div>
    </div>   
  );
}
