
import { poppins } from "@/utils/fonts";
import "./globals.css";

// React Phone Input Styles
import 'react-phone-number-input/style.css'

// leaflet Map
import 'leaflet/dist/leaflet.css'

// Toast Container
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { AuthWrapper } from "@/context/AuthContext";
import LoadingFull from "@/components/global/LoadingFull/LoadingFull";
import { ViewWrapper } from "@/context/ViewContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthWrapper>
          <ViewWrapper>
            <LoadingFull />
            <ToastContainer />
            {children}
          </ViewWrapper>
        </AuthWrapper>
      </body>
    </html>
  );
}
