
import SidebarPanel from '@/components/layout/SidebarPanel';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className={'dashboardLayout'}>
        <SidebarPanel />
        <div className='contentLayout'>
          {children}
        </div>
    </div>   
  );
}
